Added Hash to README.md
Added Hash value to custom headers. The parameter hash is needed to send it successfully.
Error: "headers" should be a "Hash" but is a "Array"